before_script:
  - export LANG=en_US.UTF-8
  - export CI_DEBUG_TRACE=true

stages:
  - test
  - release
  - deploy

.xcode-job-template: &xcode-job
  artifacts:
    when: always
    paths:
      - ./.build/release/fibs
      - ./.build/release/libagentcore.dylib
      - ./.build/release/libcpuplugin.dylib
      - ./.build/release/libenvplugin.dylib
      - ./.build/release/libhcapiplugin.dylib
      - ./.build/release/libmemplugin.dylib
      - ./fibs.zip
  tags:
    - vm-xcode10.3.0

# test:
#   <<: *xcode-job
#   stage: test
#   script:
#     - make restore-cache
#     - make bootstrap
#     - swift test
#     - make store-cache
#   except:
#     - /^no-test.*$/

build:
  <<: *xcode-job
  stage: test
  except:
    - tags
  script:
    - make restore-cache bootstrap build-release store-cache

release:
  <<: *xcode-job
  stage: release
  only:
    - tags
  script:
    - make restore-cache bootstrap build-release zip store-cache
