version: 2

references:
  workspace_setup: &workspace_setup
    attach_workspace:
      at: ~/project/appunite/fibs

  add_ssh_keys: &add_ssh_keys
    add_ssh_keys:
      fingerprints:
        - "3b:4b:79:34:50:14:18:b3:5a:21:be:19:c5:21:bf:d5"

  defaults: &defaults
    working_directory: ~/project/appunite/fibs
    macos:
      xcode: "11.0.0"
    shell: /bin/bash --login -eo pipefail
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8


jobs:
  prepare_environment:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Bootstrapping dependencies
          command: make bootstrap
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/
      - save_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods/
      - persist_to_workspace:
            root: .
            paths: .

  build:
    <<: *defaults
    steps:
      - *workspace_setup
      - run:
          name: Build library
          command: make build-release
      - store_artifacts:
          path: ./.build/release/fibs
      - store_artifacts:
          path: ./.build/release/libagentcore.dylib
      - store_artifacts:
          path: ./.build/release/libcpuplugin.dylib
      - store_artifacts:
          path: ./.build/release/libenvplugin.dylib
      - store_artifacts:
          path: ./.build/release/libhcapiplugin.dylib
      - store_artifacts:
          path: ./.build/release/libmemplugin.dylib

  release:
    <<: *defaults
    steps:
      - *workspace_setup
      - *add_ssh_keys
      - run:
          name: Build library and zip it
          command: make zip
      - run:
          name: Generate podspec based on library
          command: make generate-podspec
      - store_artifacts:
          path: ./.build/release/fibs
      - store_artifacts:
          path: ./.build/release/libagentcore.dylib
      - store_artifacts:
          path: ./.build/release/libcpuplugin.dylib
      - store_artifacts:
          path: ./.build/release/libenvplugin.dylib
      - store_artifacts:
          path: ./.build/release/libhcapiplugin.dylib
      - store_artifacts:
          path: ./.build/release/libmemplugin.dylib
      - store_artifacts:
          path: ./fibs.zip
      - persist_to_workspace:
          root: .
          paths: ./Fibs.podspec.json

  submit-cococapod:
    <<: *defaults
    steps:
      - *workspace_setup
      - *add_ssh_keys
      - run:
          name: Submit pod to Cocoapods master repo
          command: make release-cocoapods

workflows:
  version: 2
  build:
    jobs:
      - prepare_environment:
          filters:
            tags:
              ignore:
                - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/
      - build:
          requires:
            - prepare_environment
          filters:
            tags:
              ignore:
                - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/

  deploy:
    jobs:
      - prepare_environment:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/

      - release:
          requires:
            - prepare_environment
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/

      - submit-cococapod:
          requires:
            - prepare_environment
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/