name: Release

on:
  push:
    tags: '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  bootstrap_build:
    name: Bootstrap and Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Restore cached pods
        uses: actions/cache@v1.0.0
        id: restore-pods
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Restore cached gems
        uses: actions/cache@v1.0.0
        id: restore-gems
        with:
          path: vendor
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bootstrap
        run: make bootstrap

      - name: Build with release configuration
        run: make build-release

      - name: Zip the output
        run: make zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: fibs.zip
          path: fibs.zip
  release:
    name: Release
    runs-on: macOS-latest
    needs: [bootstrap_build]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: fibs.zip

      - name: Restore cached gems
        uses: actions/cache@v1.0.0
        id: restore-gems
        with:
          path: vendor
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Make gems
        if: steps.restore-gems.outputs.cache-hit != 'true'
        run: make gems

      - name: Generate podspec 
        run: make GIT_TAG=$GITHUB_REF generate-podspec

      - name: Release on Github
        uses: softprops/action-gh-release@v1
        with:
          files: fibs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload to Cocoapods
      #   env:
      #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      #   run: make release-cocoapods