name: Build & Test
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bootstrap
        run: make bootstrap
      - name: Build with release configuration
        run: make build-release